version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      UPLOAD_LIMIT: 100000000
      PMA_ARBITRARY: 1
    networks:
      - mysql_network

networks:
  mysql_network:
    external: false
    name: mysql_network
