version: "3"

services:
  service_name: #modify the service name (e.g. express:, nest; )
    container_name: "container_name" #enter your container name here
    build: .
    # command: sh -c "tail -f /dev/null" | dijalankan pertama |
    # command: sh -c "yarn dev -H 0.0.0.0 -p 3002" | dijalankan setelah node_modules terinstall
    volumes:
      - ./:/usr/src/app
    ports:
      - "3002:3002"
    networks:
      - mysql_network # add more network if there are any
      - postgresql_network
networks:
  mysql_network:
    external: true
  postgresql_network:
    external: true
