version: "3"

services:
  service_name: #modify the service name (e.g. laravel: )
    container_name: "container_name" #enter your container name here
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80 # exposed port
    networks:
      - postgresql_network

# This networks is based on the network defined in mysql_and_phpmyadmin
# Make sure you already have the image and container for db
networks:
  postgresql_network:
    external: true
