version: "3"

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - postgresql_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgresql_network

networks:
  postgresql_network:
    external: false
    name: postgresql_network
